language: java
jdk:
    - openjdk8

before_install:
    - scripts/before_install.sh

install:
    - echo "Skip install."

script:
    - scripts/build.sh

addons:
    sonarcloud:
        organization: nblxa
        token:
            secure: "A6Y4e94V2OzHPwcLsVuqeZaQ3rKibJSQQx7ZEFHxNUNdbF0cPGwZcwjmjUDbj1FXKqbV7Jy/9WXhl/wFbeI0AmFU40qBxVvy8DzowIPKh6pNxfCsgOeVxR+G7gjUbDE06JYsgsXGSl65IAn6G5LmHzcLDCkSnAK8ks2VUZ2tW1+Scs3w1fwtWZhhr9UNGRd0LyVwvclNq/fgyT7zFKqvIjvimAsJ/Yz72mR+0KNTvh626U5Q8DXrrnmFH5qAjIeXo5m32qpP7IzGe7BpDilm/mi1QfvS1Oa9VMDAUZhBQ+8a6KsNQnvOPo0oaPb2y9UMbHk0EMMzFlqfpqWnR8shHDMkPegydTBqgxaUa+agxpldwSQes3MWihHqkcWFxBawAel2BT2pqsoHbp1UJYggAP5vVm/DvjRPZd561B82KYuFiNavQin4oc1FPnCv8RUv98beDSiROpB2zabMzYyYM4qaGX62A6s+ditFzHJDnlw/5NEuyuf4vPQIkCYy3KqNzco0D69DZV+HrsVep4QrDkEhLae1DAOF5q5YulEt5NMZP2waMCjanEeEdXgtuQreMAyH1fGn5C+L3xPSu5jsoj+7rigpXn31BncIx9uW1Y2fHYCdlz2RJgtfKz5h8kqrJXHBgrnVdryi356f05phTXOo2Ac4uNLKnaWcFdm1ruI="

before_deploy:
    - export PROJECT_VERSION=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)

deploy:
    - provider: releases
      skip_cleanup: true
      draft: true
      api_key:
          secure: "xPRDkzg/dXoBvUNtonKieG4QmqzJmojNN+1B69Ms9WW67fFFMqYcWtPBMMZECwym7g3/bMRbBgaH9SmHrtc7CQRP9rzWlGXqaAn7Iy9jGNgYte3Yi0yXn2Xmb5LsQXDPMbuBSIU0CdHw6mAKE2fKL70KXTsKlJLuO5L/UkSoMqgWTHndL9rkr6gU0uDq+MdBUuCIJCmBL0CLYlee/Pw5kyJlD0J48ci56jO21KEANgz4dI3i/ZjUepwaNDPrcerhTeYRtf72Qbq8q62PgDcHDMAc8xJy5iN1N8nL0O2yqk/4smSU0oZuNnwDDXWMMFqWlFjLN1pj3m/M5AKlZtg59LqZzygV3pAFVf/9d+u/GfsLjPZffWJ6tkRrNH+lN6q15lk7bEgHY5KJK6oaKLBPve/pAKrXwpzuqt9yHGzSnCJmvd8dObE87jJg8+zbLFZZylV8VXEP1FONKnmtb+e5rrdSL8XBBPp8SujaquXp5ji5ikjxRC+Cjp+hs4/W8bahFi8xy0KJjpzkhpfJBJQ+D08K35SMRPxvKY27E9hr60xEybF+QSjsJRYi6+h4ZOXTqdjPWqigUpart04VUnba2soMQOFwNQn2ofdHV4g7aVDCtMydQduNM/h7p2mxkoqPBpZr7H3AT4Q0LrOoHKjh3MFApejeUc6jAUbOHZ02c6o="
      file:
          - turntables-core/target/turntables-core-$PROJECT_VERSION.jar
          - turntables-core/target/turntables-core-$PROJECT_VERSION.jar.asc
          - turntables-core/target/turntables-core-$PROJECT_VERSION-sources.jar
          - turntables-core/target/turntables-core-$PROJECT_VERSION-sources.jar.asc
          - turntables-core/target/turntables-core-$PROJECT_VERSION-javadoc.jar
          - turntables-core/target/turntables-core-$PROJECT_VERSION-javadoc.jar.asc
      on:
          repo: nblxa/turntables
          branch: master

    - provider: script
      skip_cleanup: true
      script: scripts/deploy.sh
      on:
          repo: nblxa/turntables
          branch: master
