language: java
jdk:
    - oraclejdk8
script:
    - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dspotbugs -Derrorprone
after_success:
    - ./mvnw clean test jacoco:report coveralls:report -e