language: java
jdk:
    - openjdk8
script:
    - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Derrorprone
after_success:
    - ./mvnw clean verify jacoco:report coveralls:report -e
